function [companyAvailabilityData] = getCompanyAvailabilityData(conn)
    % Get company availability data
    query = [
    'select '...
        'users.uid, '...
        'users.name, '...
        'field_data_field_preferred_days.field_preferred_days_value as prefday '...
    'from users '...
        'inner join users_roles '...
            'on users.uid = users_roles.uid '...
        'inner join profile '...
            'on profile.uid = users.uid '...
        'left outer join field_data_field_preferred_days '...
            'on field_data_field_preferred_days.entity_id = profile.pid '...
    'where users_roles.rid = 5'];
    res = exec(conn, query);
    res = fetch(res);
    companyAvailabilityData = res.Data;
end