function [companyData] = getCompanyData(conn)
    % Get company data
    query = [
    'select '...
        'id, '...
        'uid as company_id, '...
        'flags as prefs, '...
        'dag1, '...
        'dag2, '...
        'dag3, '...
        'num_interviewers, '...
        'pref_nat, '...
        'name '...
    'from ben_timetable_companies'];
    res = exec(conn, query);
    res = fetch(res);
    companyData = res.Data;
end
