function [companyData] = getCompanyData(conn)
    % Get student data
    query = [
    'select '...
        'id, '...
        'uid as company_id, '...
        'flags as prefs '...
    'from ben_timetable_companies'];
    res = exec(conn, query);
    res = fetch(res);
    companyData = res.Data;
end
