function [companyData] = getCompanyData(conn)
    % Get student data
    query = [
    'select '...
        'id, '...
        'company_id, '...
        'prefs_students as prefs, '...
        'dag1, '...
        'dag2, '...
        'dag3 '...
    'from timetable_students'];
    res = exec(conn, query);
    res = fetch(res);
    companyData = res.Data;
end
