function [studentData] = getStudentData(conn)
    % Get student data
    query = [
    'select '...
        'id, '...
        'student_id, '...
        'prefs_companies as prefs, '...
        'dag1, '...
        'dag2, '...
        'dag3 '...
    'from timetable_students'];
    res = exec(conn, query);
    res = fetch(res);
    studentData = res.Data;
end
