function [studentData] = getStudentData(conn)
    % Get student data
    query = [
    'select '...
        'id, '...
        'student_id, '...
        'prefs_companies as prefs, '...
        'dag1, '...
        'dag2, '...
        'dag3, '...
        'nationality, '...
        'name, '...
        'phone '...
    'from ben_timetable_students'];
    res = exec(conn, query);
    res = fetch(res);
    studentData = res.Data;
end
