% Automatically generate all students' schedules

for i = 1:program.numStuds
    fh = fopen(['../output/doc-stud-' num2str(program.studID(i)) '.tex'], 'w');

    content = [...
        '\\documentclass{article}\n'...
        '\\usepackage[T1]{fontenc}\n'...
        '\\usepackage[utf8x]{inputenc}\n'...
        '\\usepackage[top=2in, bottom=0.5in, left=0.8in, right=0.8in]{geometry}\n'...
        '\\usepackage{wallpaper}\n'...
        '\\usepackage{tabularx}\n'...
        '\\usepackage{float}\n'...
        '\\newlength\\tindent\n'...
        '\\setlength{\\tindent}{\\parindent}\n'...
        '\\setlength{\\parindent}{0pt}\n'...
        '\\setlength{\\parskip}{2em}\n'...
        '\\setlength{\\tabcolsep}{10pt}\n'...
        '\\renewcommand{\\indent}{\\hspace*{\\tindent}}\n'...
        '\\renewcommand{\\arraystretch}{1.4}\n'...
        '\\renewcommand*{\\familydefault}{\\sfdefault}\n'...
        '\\ULCornerWallPaper{1}{../briefpapier.pdf}\n'...
        '\\begin{document}\n'...
        '\\pagenumbering{gobble}\n'...
        '\\LARGE{'];
    fprintf(fh, content);
    
    name = unicode2native(program.studName{i}, 'UTF-8');
    fwrite(fh, name, 'uint8');
    
    content = [...
        '}\n\\newline\n'...
        '\\large{Interview schedule}\n'...
        '\\normalsize\n'...
     ];
    fprintf(fh, content);
    
    generateStudentTable(fh, program, schedule, i);
    fprintf(fh, '\\end{document}\n');

    fclose(fh);

    cd ../output
    system(['pdflatex doc-stud-' num2str(program.studID(i)) '.tex']);
    system(['pdflatex doc-stud-' num2str(program.studID(i)) '.tex']);
    system(['mv doc-stud-' num2str(program.studID(i)) '.pdf pdf-students/' num2str(program.studID(i)) '.pdf']);
    cd ../src
end